language: python

sudo: required

# Cache gcloud SDK
cache:
  directories:
    - "$HOME/google-cloud-sdk/"

env:
# Make sure gcloud command is on our PATH and the App Engine SDK is in the Python path
- GAE_PYTHONPATH=${HOME}/.cache/google_appengine PATH=$PATH:${HOME}/google-cloud-sdk/bin PYTHONPATH=${PYTHONPATH}:${GAE_PYTHONPATH} CLOUDSDK_CORE_DISABLE_PROMPTS=1

python:
- "2.7"
- "3.4"
- "3.5"
- "3.6"

install:
- pip install setuptools
- make install-mecab

script:
- python setup.py test
# Install Google App Engine Python SDK
- if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]] &&[ ! -d "${GAE_PYTHONPATH}" ]; then
    python _travis/fetch_gae_sdk.py $(dirname "${GAE_PYTHONPATH}");
  fi
# If the SDK is not already cached, download and unpack it
- if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]] && [ ! -d ${HOME}/google-cloud-sdk ]; then
    curl https://sdk.cloud.google.com | bash;
  fi
- if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then
    pip install -t lib -r requirements.txt;
    python gae_test_runner.py ${GAE_PYTHONPATH} --test-path=tests_gae --test-pattern=test_*.py;
  fi
